// Generated by dagger.internal.codegen.ComponentProcessor (https://google.github.io/dagger).
package com.example.omstugradebook.presentation.view.fragments.viewmodel;

import com.example.omstugradebook.data.dao.SubjectDao;
import com.example.omstugradebook.data.dao.UserDao;
import dagger.MembersInjector;
import javax.inject.Provider;

public final class GradeViewModel_MembersInjector implements MembersInjector<GradeViewModel> {
  private final Provider<UserDao> userDaoProvider;

  private final Provider<SubjectDao> subjectDaoProvider;

  public GradeViewModel_MembersInjector(
      Provider<UserDao> userDaoProvider, Provider<SubjectDao> subjectDaoProvider) {
    assert userDaoProvider != null;
    this.userDaoProvider = userDaoProvider;
    assert subjectDaoProvider != null;
    this.subjectDaoProvider = subjectDaoProvider;
  }

  public static MembersInjector<GradeViewModel> create(
      Provider<UserDao> userDaoProvider, Provider<SubjectDao> subjectDaoProvider) {
    return new GradeViewModel_MembersInjector(userDaoProvider, subjectDaoProvider);
  }

  @Override
  public void injectMembers(GradeViewModel instance) {
    if (instance == null) {
      throw new NullPointerException("Cannot inject members into a null reference");
    }
    instance.userDao = userDaoProvider.get();
    instance.subjectDao = subjectDaoProvider.get();
  }

  public static void injectUserDao(GradeViewModel instance, Provider<UserDao> userDaoProvider) {
    instance.userDao = userDaoProvider.get();
  }

  public static void injectSubjectDao(
      GradeViewModel instance, Provider<SubjectDao> subjectDaoProvider) {
    instance.subjectDao = subjectDaoProvider.get();
  }
}
