// Generated by dagger.internal.codegen.ComponentProcessor (https://google.github.io/dagger).
package com.example.omstugradebook.presentation.view.fragments.viewmodel;

import com.example.omstugradebook.data.dao.ScheduleDao;
import com.example.omstugradebook.data.dao.ScheduleOwnerDao;
import com.example.omstugradebook.data.dao.SearchScheduleDao;
import com.example.omstugradebook.data.dao.UserDao;
import dagger.MembersInjector;
import javax.inject.Provider;

public final class ScheduleViewModel_MembersInjector implements MembersInjector<ScheduleViewModel> {
  private final Provider<UserDao> userDaoProvider;

  private final Provider<ScheduleDao> scheduleDaoProvider;

  private final Provider<ScheduleOwnerDao> scheduleOwnerDaoProvider;

  private final Provider<SearchScheduleDao> searchScheduleDaoProvider;

  public ScheduleViewModel_MembersInjector(
      Provider<UserDao> userDaoProvider,
      Provider<ScheduleDao> scheduleDaoProvider,
      Provider<ScheduleOwnerDao> scheduleOwnerDaoProvider,
      Provider<SearchScheduleDao> searchScheduleDaoProvider) {
    assert userDaoProvider != null;
    this.userDaoProvider = userDaoProvider;
    assert scheduleDaoProvider != null;
    this.scheduleDaoProvider = scheduleDaoProvider;
    assert scheduleOwnerDaoProvider != null;
    this.scheduleOwnerDaoProvider = scheduleOwnerDaoProvider;
    assert searchScheduleDaoProvider != null;
    this.searchScheduleDaoProvider = searchScheduleDaoProvider;
  }

  public static MembersInjector<ScheduleViewModel> create(
      Provider<UserDao> userDaoProvider,
      Provider<ScheduleDao> scheduleDaoProvider,
      Provider<ScheduleOwnerDao> scheduleOwnerDaoProvider,
      Provider<SearchScheduleDao> searchScheduleDaoProvider) {
    return new ScheduleViewModel_MembersInjector(
        userDaoProvider, scheduleDaoProvider, scheduleOwnerDaoProvider, searchScheduleDaoProvider);
  }

  @Override
  public void injectMembers(ScheduleViewModel instance) {
    if (instance == null) {
      throw new NullPointerException("Cannot inject members into a null reference");
    }
    instance.userDao = userDaoProvider.get();
    instance.scheduleDao = scheduleDaoProvider.get();
    instance.scheduleOwnerDao = scheduleOwnerDaoProvider.get();
    instance.searchScheduleDao = searchScheduleDaoProvider.get();
  }

  public static void injectUserDao(ScheduleViewModel instance, Provider<UserDao> userDaoProvider) {
    instance.userDao = userDaoProvider.get();
  }

  public static void injectScheduleDao(
      ScheduleViewModel instance, Provider<ScheduleDao> scheduleDaoProvider) {
    instance.scheduleDao = scheduleDaoProvider.get();
  }

  public static void injectScheduleOwnerDao(
      ScheduleViewModel instance, Provider<ScheduleOwnerDao> scheduleOwnerDaoProvider) {
    instance.scheduleOwnerDao = scheduleOwnerDaoProvider.get();
  }

  public static void injectSearchScheduleDao(
      ScheduleViewModel instance, Provider<SearchScheduleDao> searchScheduleDaoProvider) {
    instance.searchScheduleDao = searchScheduleDaoProvider.get();
  }
}
